default:
    trainer: online_bc
    brain_to_imitate: <Your_Brain_Asset_Name>
    batch_size: 64
    time_horizon: 64
    summary_freq: 1000
    max_steps: 5.0e4
    batches_per_epoch: 10
    use_recurrent: false
    hidden_units: 128
    learning_rate: 3.0e-4
    num_layers: 2
    sequence_length: 32
    memory_size: 256

BananaLearning:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: BananaPlayer
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

BouncerLearning:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 10
    brain_to_imitate: BouncerPlayer
    batch_size: 16
    batches_per_epoch: 1
    num_layers: 1
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

HallwayLearning:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: HallwayPlayer
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

PushBlockLearning:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: PushBlockPlayer
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

PyramidsLearning:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: PyramidsPlayer
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

TennisLearning:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: TennisPlayer
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

StudentBrain:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: TeacherBrain
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16

StudentRecurrentBrain:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: TeacherBrain
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: true
    sequence_length: 32